class local {
    // declaring a variable.......
    int num1 = 10;
    // declaring a local class...........
    // defining a function...........
    void localClassFunction() {
        // declaring a class inside function........
        class localClass {
            void displayLocal() {
                System.out.println("The value is: " + num1); // displaying the value........
            }
        }
        // declaring the object of the class...........
        localClass obj1 = new localClass();
        // displaying class local function............
        obj1.displayLocal();
    }
}
public class COLLEDGE_LocalClasses {
    public static void main(String[] args) {
        // declaring object of local class...........
        local obj1 = new local();
        obj1.localClassFunction();
    }
}
