import java.sql.SQLOutput;

public class COLLEDGE_StringBuilderClass {
    public static void main(String[] args){
        // String Literals...
        String StringLiteralNum1 = "Ashmin";
        String StringLiteralNum2 = "Ashmin";
        // String Builders....
        String StringBuilderNum1 = new String("Ashmin");
        String StringBuilderNum2 = new String("Ashmin");
        // Checking methode....
        // '==' -> Checks, whether the references are equal or not...
        // 's1.equals()' -> Checks, whether the data of the String Variable is Equal or Not...
        System.out.println("The Literal Values: "+(StringLiteralNum1 == StringLiteralNum2)); // Returns True...
        System.out.println("The String Builder Class: "+(StringBuilderNum2 == StringBuilderNum1));
        // NOTE:- StringLiteral reference the same value, but during StringBuilder the address are different...
        // For making the Data check of the String builder...
        System.out.println("The String Builder Data Check: "+(StringBuilderNum2.equals(StringBuilderNum1)));
    }
}
